spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8112

app:
  datasource:
    main:
      driver-class-name: net.ucanaccess.jdbc.UcanaccessDriver
      jdbc-url: jdbc:ucanaccess://c:/accountsdb.accdb;showSchema=true
      username:
      password:
      pool-size:


config:
  default:
    http:
      session:
        timeout: 300
        concurrent:
          max: 1

    back-statement:
      period: 3

    pagination:
      enabled: disable
      page:
        size: 30
        index: 1
